server:
  port: 8090
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: sru_lib_management
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations: classpath:sql/schema.sql
      platform: mysql
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${email_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
hunter:
  api:
    key: ${hunter_key}
jwt:
  token: ${jwt_token}
  
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    #org.springframework: DEBUG

